### ISSUE TITLE
Android — не открывается обычный попап при отсутствии ВK-приложения на телефоне пользователя

### ISSUE THREAD

**Issue by artuska** [DrMoriarty/cordova-social-vk#34]
Cordova — 8.0.0
Android — 7.1.0

cordova-plugin-inappbrowser — 3.0.0

Если у пользователя не установлено приложение «Вконтакте», то при попытке залогиниться вываливается вот такая ошибка на Андроиде (в iOS всё хорошо — там срабатывает обычная авторизация через InAppBrowser):

```
E/PluginManager: Uncaught exception from plugin
                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                     at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:537)
                     at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
                     at com.vk.sdk.VKAccessToken.tokenFromSharedPreferences(VKAccessToken.java:236)
                     at com.vk.sdk.VKAccessToken.currentToken(VKAccessToken.java:275)
                     at com.vk.sdk.VKSdk.updateLoginState(VKSdk.java:480)
                     at com.vk.sdk.VKSdk.updateLoginState(VKSdk.java:475)
                     at com.vk.sdk.VKSdk.logout(VKSdk.java:455)
                     at ru.trilan.socialvk.SocialVk.execute(SocialVk.java:114)
                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
                     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                     at android.os.Handler.dispatchMessage(Handler.java:105)
                     at android.os.Looper.loop(Looper.java:164)
                     at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by artuska** [comment]
Так, ну, SDK вообще не работает в Кордове 8.0.0, видимо.
